### PR TITLE
Add event handler and trigger event row_will_be_added

### PR DESCRIPTION
**Pull request by brki**
This addresses #29 .

To give you an idea of how I'm using this, here is the event handler file I'm using:
```
import sqlalchemy as sa

def row_added(source_db, source_row, target_db, target_table, prioritized):
    # Nothing to do unless this is a versioned table.
    if 'version_start_date' not in source_row:
        return

    # Add all previous / future versions.
    has_previous_versions = source_row.version_start_date != source_row.version_birth_date
    has_future_versions = source_row.version_end_date is not None and source_row.id != source_row.identity
    if has_previous_versions or has_future_versions:
        versions_select = sa.sql.select([target_table]).where(sa.and_(target_table.c.identity == source_row.identity, target_table.c.id != source_row.id))
        for version_row in source_db.conn.execute(versions_select):
            source_db.create_row_in(version_row, target_db, target_table)
```

### CODE REVIEW

**Comment by brki** [comment]
Note that merging this *and* #28 will cause a merge conflict.  A correctly merged version of subsetter.py can be found here: https://github.com/brki/rdbms-subsetter/blob/event-handler-and-write-buffer-disabling/subsetter.py

**Comment by jmcarp** [comment]
This seems like a useful feature. What do you think about implementing using an existing library like blinker (https://github.com/jek/blinker), instead of custom code? Then, instead of a specific `event_module` argument, we can use something more generic like `--import`, so that modules of signal receivers are imported.

**Comment by brki** [comment]
@jmcarp that sounds like a good idea, I'll take a look at blinker.

**Comment by catherinedevlin** [comment]
Thanks for more great work!  And thanks @jmcarp for the valuable advice!

**Comment by catherinedevlin** [comment]
Replaced by https://github.com/18F/rdbms-subsetter/pull/33 (which was merged), so closing.

**Pull request closed without merging**
